# Generated by Django 2.2.4 on 2020-04-28 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
