# Generated by Django 2.2.4 on 2020-04-29 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200429_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 29, 8, 56, 1, 928949)),
        ),
    ]
